"""Contracts for the deferred SharePoint ``c&p`` workflow."""

from pathlib import Path


SHAREPOINT_HOSTNAME = "ifecloud.sharepoint.com"
SHAREPOINT_SITE_PATH = "sites/UsersofIFEBatteryLab"
SHAREPOINT_DEFAULT_DRIVE_ITEM_PATH = "General/00_Logs/Cell_Log.xlsx"
# This token-free URL is evidence metadata only. Resolution uses the Graph
# site and default-drive item endpoints, never a sharing link.
SHAREPOINT_WORKBOOK_URL = (
    f"https://{SHAREPOINT_HOSTNAME}/{SHAREPOINT_SITE_PATH}/"
    f"{SHAREPOINT_DEFAULT_DRIVE_ITEM_PATH}"
)
SOURCE_WORKBOOK_URL = SHAREPOINT_WORKBOOK_URL
SOURCE_WORKBOOK_NAME = "Cell_Log.xlsx"
SOURCE_SHEET_NAME = "c&p"
SNAPSHOT_SHEET_NAME = SOURCE_SHEET_NAME
LOCAL_SNAPSHOT_PATH = Path("source_data") / "Cell_Log_CP.xlsx"

SOURCE_FIRST_COLUMN = 1
SOURCE_LAST_COLUMN = 19
SOURCE_COLUMN_COUNT = SOURCE_LAST_COLUMN - SOURCE_FIRST_COLUMN + 1
SOURCE_RANGE = "A:S"
SOURCE_RANGE_ADDRESS = SOURCE_RANGE
BUSINESS_FIRST_COLUMN = 1
BUSINESS_LAST_COLUMN = 16
BUSINESS_COLUMN_COUNT = BUSINESS_LAST_COLUMN - BUSINESS_FIRST_COLUMN + 1
BUSINESS_RANGE = "A:P"
BUSINESS_BOUNDARY = BUSINESS_RANGE
METADATA_ROWS = (1, 2, 3)
SOURCE_METADATA_ROWS = METADATA_ROWS
HEADER_ROW = 2
SOURCE_HEADER_ROW = HEADER_ROW
UNITS_ROW = 3
SOURCE_UNITS_ROW = UNITS_ROW
DATA_START_ROW = 4
SOURCE_DATA_START_ROW = DATA_START_ROW
KEY_COLUMN = 1
SOURCE_KEY_COLUMN = "A"
SOURCE_KEY_COLUMN_LETTER = "A"
KEY_HEADER = "key"
DATABASE_KEY_COLUMN = 1
DATABASE_KEY_HEADER = "id"
